var percapta =
  [{
  	"uf": "RO",
  	"num_pop_per_osc": 526,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "AC",
  	"num_pop_per_osc": 706,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "AM",
  	"num_pop_per_osc": 1272,
  	"cd_int_pop_per_osc": 4
  }, {
  	"uf": "RR",
  	"num_pop_per_osc": 1101,
  	"cd_int_pop_per_osc": 4
  }, {
  	"uf": "PA",
  	"num_pop_per_osc": 1074,
  	"cd_int_pop_per_osc": 3
  }, {
  	"uf": "AP",
  	"num_pop_per_osc": 1449,
  	"cd_int_pop_per_osc": 5
  }, {
  	"uf": "TO",
  	"num_pop_per_osc": 571,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "MA",
  	"num_pop_per_osc": 829,
  	"cd_int_pop_per_osc": 3
  }, {
  	"uf": "PI",
  	"num_pop_per_osc": 508,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "CE",
  	"num_pop_per_osc": 523,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "RN",
  	"num_pop_per_osc": 712,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "PB",
  	"num_pop_per_osc": 535,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "PE",
  	"num_pop_per_osc": 794,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "AL",
  	"num_pop_per_osc": 1214,
  	"cd_int_pop_per_osc": 4
  }, {
  	"uf": "SE",
  	"num_pop_per_osc": 652,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "BA",
  	"num_pop_per_osc": 618,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "MG",
  	"num_pop_per_osc": 459,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "ES",
  	"num_pop_per_osc": 397,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "RJ",
  	"num_pop_per_osc": 497,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "SP",
  	"num_pop_per_osc": 547,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "PR",
  	"num_pop_per_osc": 394,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "SC",
  	"num_pop_per_osc": 271,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "RS",
  	"num_pop_per_osc": 316,
  	"cd_int_pop_per_osc": 1
  }, {
  	"uf": "MS",
  	"num_pop_per_osc": 542,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "MT",
  	"num_pop_per_osc": 557,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "GO",
  	"num_pop_per_osc": 756,
  	"cd_int_pop_per_osc": 2
  }, {
  	"uf": "DF",
  	"num_pop_per_osc": 627,
  	"cd_int_pop_per_osc": 2
  }];
